package eu.choreos.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-27T12:40:48.601-03:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://service.choreos.eu/", name = "CarParkingWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CarParkingWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLongitude", targetNamespace = "http://service.choreos.eu/", className = "eu.choreos.service.GetLongitude")
    @WebMethod
    @ResponseWrapper(localName = "getLongitudeResponse", targetNamespace = "http://service.choreos.eu/", className = "eu.choreos.service.GetLongitudeResponse")
    public java.lang.String getLongitude(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCarParkCode", targetNamespace = "http://service.choreos.eu/", className = "eu.choreos.service.GetCarParkCode")
    @WebMethod
    @ResponseWrapper(localName = "getCarParkCodeResponse", targetNamespace = "http://service.choreos.eu/", className = "eu.choreos.service.GetCarParkCodeResponse")
    public java.lang.String getCarParkCode(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLatitude", targetNamespace = "http://service.choreos.eu/", className = "eu.choreos.service.GetLatitude")
    @WebMethod
    @ResponseWrapper(localName = "getLatitudeResponse", targetNamespace = "http://service.choreos.eu/", className = "eu.choreos.service.GetLatitudeResponse")
    public java.lang.String getLatitude(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
