
/*
 * 
 */

package eu.choreos.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-27T12:40:48.958-03:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "CarParkingWSService", 
                  wsdlLocation = "http://localhost:1234/carParkingWS?wsdl",
                  targetNamespace = "http://service.choreos.eu/") 
public class CarParkingWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.choreos.eu/", "CarParkingWSService");
    public final static QName CarParkingWSPort = new QName("http://service.choreos.eu/", "CarParkingWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1234/carParkingWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CarParkingWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:1234/carParkingWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CarParkingWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CarParkingWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarParkingWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns CarParkingWS
     */
    @WebEndpoint(name = "CarParkingWSPort")
    public CarParkingWS getCarParkingWSPort() {
        return super.getPort(CarParkingWSPort, CarParkingWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarParkingWS
     */
    @WebEndpoint(name = "CarParkingWSPort")
    public CarParkingWS getCarParkingWSPort(WebServiceFeature... features) {
        return super.getPort(CarParkingWSPort, CarParkingWS.class, features);
    }

}
