
package br.batcave;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldWS", targetNamespace = "http://batcave.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloTo", targetNamespace = "http://batcave.br/", className = "br.batcave.SayHelloTo")
    @ResponseWrapper(localName = "sayHelloToResponse", targetNamespace = "http://batcave.br/", className = "br.batcave.SayHelloToResponse")
    public String sayHelloTo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
