
/*
 * 
 */

package eu.choreos.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-28T01:19:47.214-03:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "InteractiveGuide", 
                  wsdlLocation = "http://localhost:8001/services/interactiveGuide?wsdl",
                  targetNamespace = "http://api.choreos.eu/") 
public class InteractiveGuide extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api.choreos.eu/", "InteractiveGuide");
    public final static QName InteractiveGuidePort = new QName("http://api.choreos.eu/", "InteractiveGuidePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8001/services/interactiveGuide?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InteractiveGuide.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8001/services/interactiveGuide?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InteractiveGuide(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InteractiveGuide(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InteractiveGuide() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns InteractiveGuidePortType
     */
    @WebEndpoint(name = "InteractiveGuidePort")
    public InteractiveGuidePortType getInteractiveGuidePort() {
        return super.getPort(InteractiveGuidePort, InteractiveGuidePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InteractiveGuidePortType
     */
    @WebEndpoint(name = "InteractiveGuidePort")
    public InteractiveGuidePortType getInteractiveGuidePort(WebServiceFeature... features) {
        return super.getPort(InteractiveGuidePort, InteractiveGuidePortType.class, features);
    }

}
