package com.safetrip.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-27T19:21:26.883-03:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://service.safetrip.com/", name = "WebTrip")
@XmlSeeAlso({ObjectFactory.class})
public interface WebTrip {

    @WebResult(name = "result", targetNamespace = "")
    @Action(input = "//service.safetrip.com/WebTrip/addFlightRequest", output = "//service.safetrip.com/WebTrip/addFlightResponse")
    @RequestWrapper(localName = "addFlight", targetNamespace = "http://service.safetrip.com/", className = "com.safetrip.service.AddFlight")
    @WebMethod
    @ResponseWrapper(localName = "addFlightResponse", targetNamespace = "http://service.safetrip.com/", className = "com.safetrip.service.AddFlightResponse")
    public java.lang.String addFlight(
        @WebParam(name = "flight", targetNamespace = "")
        com.safetrip.service.Flight flight
    );

    @WebResult(name = "flight", targetNamespace = "")
    @Action(input = "//service.safetrip.com/WebTrip/getFlightRequest", output = "//service.safetrip.com/WebTrip/getFlightResponse")
    @RequestWrapper(localName = "getFlight", targetNamespace = "http://service.safetrip.com/", className = "com.safetrip.service.GetFlight")
    @WebMethod
    @ResponseWrapper(localName = "getFlightResponse", targetNamespace = "http://service.safetrip.com/", className = "com.safetrip.service.GetFlightResponse")
    public com.safetrip.service.Flight getFlight(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );
}
