package eu.choreos.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-28T12:05:02.148-03:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://api.choreos.eu/", name = "CarParkReservationPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CarParkReservationPortType {

    @WebResult(name = "return", targetNamespace = "http://api.choreos.eu/")
    @RequestWrapper(localName = "setPassengerInfo", targetNamespace = "http://api.choreos.eu/", className = "eu.choreos.api.SetPassengerInfo")
    @WebMethod
    @ResponseWrapper(localName = "setPassengerInfoResponse", targetNamespace = "http://api.choreos.eu/", className = "eu.choreos.api.SetPassengerInfoResponse")
    public java.lang.String setPassengerInfo(
        @WebParam(name = "arg0", targetNamespace = "http://api.choreos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.choreos.eu/")
        java.lang.String arg1
    );
}
